language: csharp
solution: Booma.Library.sln
install:
  - nuget restore Booma.Library.sln -NoCache -NonInteractive -ConfigFile Nuget.config
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - ./build.sh
  - ./test.sh