language: csharp
solution: Booma.Library.sln
install:
  - nuget restore Booma.Library.sln -ConfigFile NuGet.config
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

before_script:
  - chmod +x ./test.sh
  - chmod +x ./build.sh

script:
  - ./build.sh
  - ./test.sh