language: csharp
solution: ./Booma.Client.ServerSelection.sln

notifications:
  slack: boomanationteam:sPQHUqEWA3wTaB9IKOSxe2f1

env:
  - PROJNAME=Booma.Client.ServerSelection

install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory tests/testrunner
  - nuget restore Booma.Client.ServerSelection.sln -ConfigFile NuGet.config

before_script:
  - chmod +x ./Build.sh

script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./Build.sh