language: csharp
solution: ./Booma.Combat.Formula.Server.sln

notifications:
  slack: boomanationteam:sPQHUqEWA3wTaB9IKOSxe2f1

install:
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory tests/testrunner
  - nuget restore Booma.Combat.Formula.Server.sln -ConfigFile NuGet.config

before_script:
  - chmod +x ./tests/RunTests.sh
  - chmod +x ./Build.sh

script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./Build.sh
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"